LUT = {
  "AGENTS": [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
  ],
  "VLO": {
    "CLASS": {
      "ID": {
        "-1": "3A",
        "-2": "3B",
        "-29": "2A",
        "-3": "3C",
        "-30": "2B",
        "-31": "2C",
        "-32": "2D",
        "-33": "2E",
        "-34": "2F",
        "-35": "2G",
        "-36": "2H",
        "-37": "2Ag",
        "-38": "2Bg",
        "-39": "2Cg",
        "-4": "3D",
        "-40": "2Dg",
        "-41": "2Eg",
        "-42": "2Fg",
        "-43": "2Gg",
        "-44": "2Hg",
        "-45": "1A",
        "-46": "1B",
        "-47": "1C",
        "-48": "1D",
        "-49": "1E",
        "-5": "3E",
        "-50": "1F",
        "-51": "1G",
        "-52": "1H",
        "-6": "3F",
        "-7": "3G",
        "-8": "3H"
      },
      "IDR": {
        "1A": "-45",
        "1B": "-46",
        "1C": "-47",
        "1D": "-48",
        "1E": "-49",
        "1F": "-50",
        "1G": "-51",
        "1H": "-52",
        "2A": "-29",
        "2AG": "-37",
        "2Ag": "-37",
        "2B": "-30",
        "2BG": "-38",
        "2Bg": "-38",
        "2C": "-31",
        "2CG": "-39",
        "2Cg": "-39",
        "2D": "-32",
        "2DG": "-40",
        "2Dg": "-40",
        "2E": "-33",
        "2EG": "-41",
        "2Eg": "-41",
        "2F": "-34",
        "2FG": "-42",
        "2Fg": "-42",
        "2G": "-35",
        "2GG": "-43",
        "2Gg": "-43",
        "2H": "-36",
        "2HG": "-44",
        "2Hg": "-44",
        "3A": "-1",
        "3B": "-2",
        "3C": "-3",
        "3D": "-4",
        "3E": "-5",
        "3F": "-6",
        "3G": "-7",
        "3H": "-8"
      },
      "ROOM": {
        "ID": {
          "-1": "1",
          "-10": "14",
          "-11": "15",
          "-12": "16",
          "-13": "17",
          "-14": "18",
          "-15": "19",
          "-16": "20",
          "-17": "21",
          "-18": "22",
          "-19": "23",
          "-2": "2",
          "-20": "24",
          "-21": "25",
          "-22": "26",
          "-23": "27",
          "-24": "28",
          "-25": "29",
          "-26": "31",
          "-27": "32",
          "-28": "35",
          "-29": "36",
          "-3": "3",
          "-30": "37",
          "-31": "33",
          "-32": "aula",
          "-33": "01",
          "-34": "02",
          "-35": "03",
          "-36": "04",
          "-37": "inf1",
          "-38": "inf2",
          "-39": "siłownia",
          "-4": "5",
          "-42": "dH1",
          "-43": "DH2",
          "-44": "DH3",
          "-48": "CUJ 1",
          "-49": "piw_prawa",
          "-50": "piw_lewa",
          "-51": "par_lewy",
          "-52": "par_prawy",
          "-53": "I lewy",
          "-54": "I prawy",
          "-55": "II lewy",
          "-56": "II prawy",
          "-57": "CUJ2",
          "-58": "CUJ3",
          "-59": "CUJ4",
          "-6": "13",
          "-60": "Biblio",
          "-61": "mpn",
          "-63": "DPN",
          "-64": "g_mala",
          "-65": "g_duza",
          "-66": "A1",
          "-67": "A2",
          "-68": "A3",
          "-69": "A4",
          "-7": "13A",
          "-70": "A5",
          "-71": "A6",
          "-72": "A7",
          "-73": "A8",
          "-74": "A9",
          "-75": "A10",
          "-76": "A11",
          "-77": "13B",
          "-78": "PN",
          "-79": "IP",
          "-9": "13C"
        }
      }
    },
    "SUBJECTS": {
      "ID": {
        "LONG": {
          "-1": "Język polski o",
          "-10": "Język rosyjski",
          "-11": "Język hiszpański",
          "-12": "Język włoski",
          "-13": "j.chiński",
          "-14": "Historia",
          "-15": "Historia - R",
          "-16": "Historia i społeczeństwo o",
          "-17": "Historia i społeczeństwo",
          "-18": "Wiedza o społeczeństwie",
          "-19": "Wiedza o społeczeństwie - R",
          "-2": "Język polski",
          "-20": "Wiedza o kulturze",
          "-21": "Matematyka o",
          "-22": "Matematyka",
          "-23": "Matematyka - R",
          "-24": "Fizyka z astronomią",
          "-25": "Fizyka z astronomią - R",
          "-27": "Fizyka stosowana",
          "-28": "Chemia",
          "-29": "Chemia - R o",
          "-3": "Język polski - R",
          "-30": "Chemia - R",
          "-31": "Biologia",
          "-32": "Biologia - R o",
          "-33": "Biologia - R",
          "-34": "Biologia dla chemików",
          "-35": "Geografia",
          "-36": "Geografia - R",
          "-37": "Przyroda",
          "-38": "Podstawy przedsiębiorczości",
          "-39": "Informatyka",
          "-4": "Język obcy I",
          "-40": "informatyka o",
          "-41": "Informatyka - R",
          "-42": "Informatyka - S",
          "-43": "Wychowanie fizyczne",
          "-44": "Edukacja dla bezpieczeństwa",
          "-45": "Godzina z wychowawc ą  o",
          "-46": "Godzina z wychowawcą",
          "-47": "Etyka",
          "-48": "Religia o ",
          "-49": "Religia",
          "-5": "Konwersatorium",
          "-50": "Podstawy historii sztuki",
          "-51": "Wychowanie do życia w rodzinie",
          "-52": "Zniżka - dyrektor",
          "-53": "Zniżka - wicedyrektor",
          "-54": "Obowiązki bibliotekarza",
          "-55": "Obowiązki pedagoga",
          "-56": "Obowiązki psychologa",
          "-57": "Zajęcia laboratoryjne UJ",
          "-58": "Zajęcia laboratoryjne UJ 1",
          "-59": "Zajęcia międzyoddziałowe - chemia",
          "-6": "Język obcy II",
          "-60": "Nauczanie indywidualne",
          "-61": "algorytmika o",
          "-62": "algorytmika",
          "-63": "Zajęcia pozalekcyjne artystyczne",
          "-64": "Doradztwo zawodowe",
          "-65": "Kultura Chin",
          "-66": "Urlop dla poratowania zdrowia",
          "-67": "rewalidacja",
          "-7": "Język niemiecki",
          "-71": "Filozofia",
          "-72": "Fizyka UJ",
          "-73": "zaj. wyrównawcze",
          "-74": "szcz. uzdolnieni",
          "-75": "Fakultet matematyczny",
          "-76": "UJ Polski",
          "-77": "Chmura",
          "-78": "Konwersatorium z jęyka angielskiego",
          "-79": "Filozofia z elementami psychologii",
          "-8": "Język angielski",
          "-80": "Konwersatorium z języka niemieckiego",
          "-81": "Konwersatorium z języka francuskiego",
          "-82": "Konwersatorium z języka hizpańskiego",
          "-9": "Język francuski"
        },
        "SHORT": {
          "-1": "J. polski",
          "-10": "j.rosyjski",
          "-11": "j.hiszpański",
          "-12": "j.włoski",
          "-13": "j.chiński",
          "-14": "historia",
          "-15": "R - historia",
          "-16": "his",
          "-17": "HiS",
          "-18": "wos",
          "-19": "R - WoS",
          "-2": "j.polski",
          "-20": "kultura",
          "-21": "Matematyka",
          "-22": "matematyka",
          "-23": "R - matematy",
          "-24": "fizyka",
          "-25": "R - fizyka",
          "-27": "S - fizyka",
          "-28": "chemia",
          "-29": "Chemia",
          "-3": "R - j. polsk",
          "-30": "R - chemia",
          "-31": "biologia",
          "-32": "Biologia",
          "-33": "R - biologia",
          "-34": "Biol. dla ch",
          "-35": "geografia",
          "-36": "R - geografi",
          "-37": "przyroda",
          "-38": "przedsięb.",
          "-39": "informatyka",
          "-4": "j.obcy I",
          "-40": "Informatyka",
          "-41": "R - informat",
          "-42": "S - inform.",
          "-43": "wf",
          "-44": "EdB",
          "-45": "Godz. wych",
          "-46": "godz.wych",
          "-47": "etyka",
          "-48": "Religia o",
          "-49": "religia",
          "-5": "K - j. obcy ",
          "-50": "historia szt",
          "-51": "wych.rodz.",
          "-52": "dyrektor",
          "-53": "wicedyr. dyd",
          "-54": "biblioteka",
          "-55": "pedagog",
          "-56": "psycholog",
          "-57": "chemia 2c UJ",
          "-58": "chemia 1c UJ",
          "-59": "MO",
          "-6": "j. obcy II",
          "-60": "naucz.indyw.",
          "-61": "Algorytmika",
          "-62": "algorytmika",
          "-63": "chór",
          "-64": "Dor. zawod.",
          "-65": "Chiny",
          "-66": "urlop zdrow.",
          "-67": "rewalidacja",
          "-7": "J.niemiecki",
          "-71": "filozofia",
          "-72": "Fizyka-UJ",
          "-73": "zaj. wyr.",
          "-74": "szcz. uzdol.",
          "-75": "Fm",
          "-76": "UP",
          "-77": "C",
          "-78": "KonA",
          "-79": "filozofia z",
          "-8": "j.angielski",
          "-80": "KonN",
          "-81": "KonF",
          "-82": "KonH",
          "-9": "j.francuski"
        }
      }
    },
    "TEACHERS": {
      "ID": {
        "SHORT": {
          "-1": "Chruściel",
          "-10": "Dudek",
          "-101": "Faryna",
          "-102": "Bałucka",
          "-103": "Bednarek",
          "-104": "Micygała",
          "-105": "cV",
          "-106": "Chodacka",
          "-108": "Koszałka",
          "-109": "Niemczyk",
          "-11": "Kandyba",
          "-111": "Kamińska",
          "-112": "Maruszczak",
          "-114": "Pieniążek",
          "-115": "Pezarski",
          "-116": "Kołdras",
          "-118": "MS",
          "-120": "Mach",
          "-121": "Wy",
          "-122": "V1",
          "-123": "AV",
          "-124": "3V",
          "-125": "Słowikowska",
          "-126": "Malcharek",
          "-127": "Andryka",
          "-128": "Jachowicz",
          "-129": "Kmiecik",
          "-130": "Stokłosa",
          "-131": "Stypuła",
          "-132": "Stańczyk",
          "-133": "Kopiec",
          "-134": "ZV",
          "-135": "pV",
          "-136": "Szarek",
          "-137": "SzymlakE",
          "-138": "Gluszko",
          "-139": "Czyrnecka",
          "-14": "Olszewska",
          "-140": "Marcińska",
          "-141": "Gluszko",
          "-142": "MS",
          "-143": "Myślińska",
          "-15": "Oniszczuk",
          "-16": "Ostrowska",
          "-17": "Płaneta",
          "-18": "Sowińska",
          "-20": "Zagórny",
          "-21": "Rabiega",
          "-22": "Pabian",
          "-24": "SM",
          "-25": "Wojtasiewicz",
          "-26": "Zborczyńska",
          "-27": "Bajer",
          "-28": "Kotula",
          "-29": "Kapłon",
          "-3": "Jantos",
          "-30": "Szewczyk",
          "-31": "Wadowska",
          "-32": "Rojewska",
          "-33": "Kurzawińska",
          "-34": "Pach",
          "-35": "Sokólska",
          "-36": "Szklarska",
          "-37": "Boroń",
          "-38": "Garlicki",
          "-39": "Jaworski",
          "-4": "Kos",
          "-40": "Kobylec",
          "-42": "Drabczyk",
          "-43": "Borcz",
          "-44": "Dymel",
          "-45": "Gunia",
          "-46": "Kaszuba",
          "-47": "Kielar",
          "-48": "Kraszewski",
          "-49": "Niedźwiedź",
          "-52": "Pietras",
          "-53": "Zając",
          "-54": "Fryt",
          "-55": "Król",
          "-56": "Przybylski",
          "-58": "Gełdon",
          "-59": "Kręgiel",
          "-6": "Ostachowska-Kos",
          "-60": "Zuchmańska",
          "-61": "Osuch",
          "-62": "Słowiak",
          "-64": "Brezdeń",
          "-67": "Duraj",
          "-68": "Gś",
          "-7": "Pasieka",
          "-70": "Kabłak",
          "-71": "Piekarska",
          "-72": "Kosiński",
          "-73": "Stolarski",
          "-74": "Studnicki",
          "-75": "Berkowicz",
          "-76": "Gł",
          "-77": "Dziedzic",
          "-79": "Kieres",
          "-81": "Ptak-Grzesik",
          "-82": "Zawadzki",
          "-83": "Sokołowska",
          "-84": "Marcinek",
          "-85": "Kulczycki",
          "-86": "Burek",
          "-87": "Kobos",
          "-88": "Herman",
          "-9": "Adamska",
          "-91": "PU",
          "-92": "Ciepielowska",
          "-94": "UA",
          "-95": "Kaniecka",
          "-96": "An",
          "-98": "Gorczyca"
        }
      }
    },
    "TIME": {
      "DATA": {
        "0": {
          "begin": "07:10",
          "end": "07:55"
        },
        "1": {
          "begin": "08:00",
          "end": "08:45"
        },
        "10": {
          "begin": "16:30",
          "end": "17:15"
        },
        "2": {
          "begin": "09:00",
          "end": "09:45"
        },
        "3": {
          "begin": "10:00",
          "end": "10:45"
        },
        "4": {
          "begin": "11:00",
          "end": "11:45"
        },
        "5": {
          "begin": "12:00",
          "end": "12:45"
        },
        "6": {
          "begin": "13:00",
          "end": "13:45"
        },
        "7": {
          "begin": "14:00",
          "end": "14:45"
        },
        "8": {
          "begin": "14:50",
          "end": "15:35"
        },
        "9": {
          "begin": "15:40",
          "end": "16:25"
        }
      },
      "MAP": {
        "07:10": "0",
        "08:00": "1",
        "09:00": "2",
        "10:00": "3",
        "11:00": "4",
        "12:00": "5",
        "13:00": "6",
        "14:00": "7",
        "14:50": "8",
        "15:40": "9",
        "16:30": "10"
      },
      "RMAP": {
        "0": "07:10",
        "1": "08:00",
        "10": "16:30",
        "2": "09:00",
        "3": "10:00",
        "4": "11:00",
        "5": "12:00",
        "6": "13:00",
        "7": "14:00",
        "8": "14:50",
        "9": "15:40"
      }
    }
  }
}